// @vitest-environment node
//
// Coverage for `lib/sso/cert-validation.ts`. We load static test PEMs
// generated by `scripts/generate-saml-test-certs.sh` (run once,
// committed under tests/fixtures/saml/certs/) and assert each one
// produces the expected validation outcome — including the fingerprint,
// signature-algorithm OID extraction, and key-strength check.
//
// The PEMs are stable across runs, so the tests are deterministic. The
// generation script is committed alongside them so it's clear how each
// fixture was produced — we never check in opaque binary blobs.

import { describe, it, expect, beforeAll } from 'vitest'
import * as fs from 'node:fs'
import * as path from 'node:path'

import { validateSigningCert } from '@/lib/sso/cert-validation'

const CERT_DIR = path.resolve(__dirname, '../../fixtures/saml/certs')

function loadCertBase64(filename: string): string {
  const pem = fs.readFileSync(path.join(CERT_DIR, filename), 'utf8')
  return pem
    .replace(/-----BEGIN CERTIFICATE-----/g, '')
    .replace(/-----END CERTIFICATE-----/g, '')
    .replace(/\s+/g, '')
}

describe('validateSigningCert — base64 input handling', () => {
  it('rejects empty string', () => {
    const r = validateSigningCert('')
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.errorCode).toBe('CERT_DECODE_FAILED')
  })

  it('rejects whitespace-only input', () => {
    const r = validateSigningCert('   \n   \t   ')
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.errorCode).toBe('CERT_DECODE_FAILED')
  })

  it('rejects characters outside the base64 alphabet', () => {
    const r = validateSigningCert('NOT-VALID-BASE64-CHARS!@#$')
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.errorCode).toBe('CERT_DECODE_FAILED')
  })

  it('rejects valid base64 that does not parse as X.509', () => {
    // base64("hello world") is valid base64 but not a cert.
    const r = validateSigningCert(Buffer.from('hello world').toString('base64'))
    expect(r.ok).toBe(false)
    if (!r.ok) expect(r.errorCode).toBe('CERT_PARSE_FAILED')
  })

  it('tolerates whitespace inside the base64 (XML pretty-printing)', () => {
    // Insert newlines + spaces every 64 chars, simulating PEM-like wrap.
    const raw = loadCertBase64('valid-sha256-rsa-2048.pem')
    const wrapped = raw.match(/.{1,64}/g)!.join('\n  ')
    const r = validateSigningCert(wrapped)
    expect(r.ok).toBe(true)
  })
})

describe('validateSigningCert — valid certs (acceptance)', () => {
  let validCert: string
  let validSha384: string
  let validEcP256: string
  let validEd25519: string

  beforeAll(() => {
    validCert = loadCertBase64('valid-sha256-rsa-2048.pem')
    validSha384 = loadCertBase64('valid-sha384-rsa-3072.pem')
    validEcP256 = loadCertBase64('valid-ecdsa-p256.pem')
    validEd25519 = loadCertBase64('valid-ed25519.pem')
  })

  it('accepts SHA-256 with RSA-2048', () => {
    const r = validateSigningCert(validCert)
    expect(r.ok).toBe(true)
    if (r.ok) {
      expect(r.signature_algorithm).toBe('sha256WithRSAEncryption')
      expect(r.key_type).toBe('rsa')
      expect(r.key_size_bits).toBe(2048)
      expect(r.fingerprint_sha256).toMatch(/^[0-9a-f]{64}$/)
      expect(r.subject).toContain('Settle SAML Test Valid SHA-256 RSA-2048')
      expect(new Date(r.not_before).getTime()).toBeLessThan(Date.now())
      expect(new Date(r.not_after).getTime()).toBeGreaterThan(Date.now())
    }
  })

  it('accepts SHA-384 with RSA-3072', () => {
    const r = validateSigningCert(validSha384)
    expect(r.ok).toBe(true)
    if (r.ok) {
      expect(r.signature_algorithm).toBe('sha384WithRSAEncryption')
      expect(r.key_type).toBe('rsa')
      expect(r.key_size_bits).toBe(3072)
    }
  })

  it('accepts ECDSA P-256 with SHA-256', () => {
    const r = validateSigningCert(validEcP256)
    expect(r.ok).toBe(true)
    if (r.ok) {
      expect(r.signature_algorithm).toBe('ecdsa-with-SHA256')
      expect(r.key_type).toBe('ec')
      expect(r.key_curve).toBe('prime256v1')
    }
  })

  it('accepts Ed25519', () => {
    const r = validateSigningCert(validEd25519)
    expect(r.ok).toBe(true)
    if (r.ok) {
      expect(r.signature_algorithm).toBe('Ed25519')
      expect(r.key_type).toBe('ed25519')
    }
  })

  it('produces a stable fingerprint for the same cert across calls', () => {
    const r1 = validateSigningCert(loadCertBase64('valid-sha256-rsa-2048.pem'))
    const r2 = validateSigningCert(loadCertBase64('valid-sha256-rsa-2048.pem'))
    expect(r1.ok && r2.ok).toBe(true)
    if (r1.ok && r2.ok) {
      expect(r1.fingerprint_sha256).toBe(r2.fingerprint_sha256)
    }
  })

  it('produces different fingerprints for different certs', () => {
    const r1 = validateSigningCert(loadCertBase64('valid-sha256-rsa-2048.pem'))
    const r2 = validateSigningCert(loadCertBase64('valid-sha384-rsa-3072.pem'))
    expect(r1.ok && r2.ok).toBe(true)
    if (r1.ok && r2.ok) {
      expect(r1.fingerprint_sha256).not.toBe(r2.fingerprint_sha256)
    }
  })
})

describe('validateSigningCert — deprecated signature algorithms', () => {
  it('rejects SHA-1 with RSA', () => {
    const r = validateSigningCert(loadCertBase64('sha1-rsa-2048.pem'))
    expect(r.ok).toBe(false)
    if (!r.ok) {
      expect(r.errorCode).toBe('CERT_WEAK_SIGNATURE_ALG')
      expect(r.error).toContain('sha1WithRSAEncryption')
    }
  })

  it('rejects MD5 with RSA', () => {
    const r = validateSigningCert(loadCertBase64('md5-rsa-2048.pem'))
    expect(r.ok).toBe(false)
    if (!r.ok) {
      expect(r.errorCode).toBe('CERT_WEAK_SIGNATURE_ALG')
      expect(r.error).toContain('md5WithRSAEncryption')
    }
  })
})

describe('validateSigningCert — weak keys', () => {
  it('rejects RSA-1024 even when signed with SHA-256', () => {
    const r = validateSigningCert(loadCertBase64('weak-rsa-1024.pem'))
    expect(r.ok).toBe(false)
    if (!r.ok) {
      expect(r.errorCode).toBe('CERT_WEAK_KEY')
      expect(r.error).toMatch(/2048/)
    }
  })

  it('rejects EC P-192 (secp192r1)', () => {
    const r = validateSigningCert(loadCertBase64('weak-ec-p192.pem'))
    expect(r.ok).toBe(false)
    if (!r.ok) {
      expect(r.errorCode).toBe('CERT_WEAK_KEY')
      expect(r.error).toMatch(/P-256|P-384|P-521/)
    }
  })
})

describe('validateSigningCert — validity window', () => {
  it('rejects expired certs with CERT_EXPIRED', () => {
    const r = validateSigningCert(loadCertBase64('expired-rsa-2048.pem'))
    expect(r.ok).toBe(false)
    if (!r.ok) {
      expect(r.errorCode).toBe('CERT_EXPIRED')
      // The fixture cert expires on 2020-01-02.
      expect(r.error).toContain('2020')
    }
  })

  it('rejects certs whose notBefore is in the future', () => {
    const r = validateSigningCert(loadCertBase64('not-yet-valid-rsa-2048.pem'))
    expect(r.ok).toBe(false)
    if (!r.ok) {
      expect(r.errorCode).toBe('CERT_NOT_YET_VALID')
      // The fixture cert's notBefore is 2099-01-01.
      expect(r.error).toContain('2099')
    }
  })
})
