import {
  AlignmentType,
  BorderStyle,
  Document,
  Footer,
  Header,
  HeadingLevel,
  LevelFormat,
  Packer,
  PageBreak,
  PageNumber,
  Paragraph,
  ShadingType,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from 'docx'

export interface ReportMeta {
  projectName: string
  generatedDate: string
  readinessScore: number
  readinessLabel: string
}

type DocChild = Paragraph | Table

// ── Public entry point ────────────────────────────────────────────────────────

export async function buildReadinessDocx(markdownContent: string, meta: ReportMeta): Promise<Buffer> {
  const children: DocChild[] = []

  // Title page
  children.push(...buildTitlePage(meta))

  // Report sections parsed from Claude's Markdown
  const sections = parseMarkdownSections(markdownContent)
  for (const section of sections) {
    children.push(buildSectionHeading(section.title))
    children.push(...parseContentToDocChildren(section.content))
    // Spacing paragraph between sections
    children.push(new Paragraph({ children: [], spacing: { after: 200 } }))
  }

  const scoreColor =
    meta.readinessScore >= 80 ? '16A34A' : meta.readinessScore >= 50 ? 'CA8A04' : 'DC2626'

  const doc = new Document({
    styles: {
      default: {
        document: {
          run: { font: 'Arial', size: 22 }, // 11pt
        },
      },
      paragraphStyles: [
        {
          id: 'Heading1',
          name: 'Heading 1',
          basedOn: 'Normal',
          next: 'Normal',
          quickFormat: true,
          run: { size: 28, bold: true, font: 'Arial', color: '1E293B' },
          paragraph: { spacing: { before: 400, after: 160 }, outlineLevel: 0 },
        },
        {
          id: 'Heading2',
          name: 'Heading 2',
          basedOn: 'Normal',
          next: 'Normal',
          quickFormat: true,
          run: { size: 24, bold: true, font: 'Arial', color: '334155' },
          paragraph: { spacing: { before: 280, after: 120 }, outlineLevel: 1 },
        },
      ],
    },
    numbering: {
      config: [
        {
          reference: 'bullets',
          levels: [
            {
              level: 0,
              format: LevelFormat.BULLET,
              text: '\u2022',
              alignment: AlignmentType.LEFT,
              style: {
                paragraph: { indent: { left: 720, hanging: 360 } },
                run: { font: 'Arial', size: 22 },
              },
            },
          ],
        },
      ],
    },
    sections: [
      {
        properties: {
          page: {
            size: { width: 12240, height: 15840 }, // US Letter
            margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 }, // 1 inch
          },
        },
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                alignment: AlignmentType.RIGHT,
                children: [
                  new TextRun({
                    text: `${meta.projectName} — Migration Readiness Report`,
                    size: 16,
                    color: '94A3B8',
                    font: 'Arial',
                  }),
                ],
                border: {
                  bottom: { style: BorderStyle.SINGLE, size: 1, color: 'E2E8F0', space: 4 },
                },
              }),
            ],
          }),
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                border: {
                  top: { style: BorderStyle.SINGLE, size: 1, color: 'E2E8F0', space: 4 },
                },
                children: [
                  new TextRun({ text: 'Generated by Mine  ·  Page ', size: 16, color: '94A3B8', font: 'Arial' }),
                  new TextRun({ children: [PageNumber.CURRENT], size: 16, color: '94A3B8', font: 'Arial' }),
                  new TextRun({ text: ' of ', size: 16, color: '94A3B8', font: 'Arial' }),
                  new TextRun({ children: [PageNumber.TOTAL_PAGES], size: 16, color: '94A3B8', font: 'Arial' }),
                ],
              }),
            ],
          }),
        },
        children,
      },
    ],
  })

  return Buffer.from(await Packer.toBuffer(doc))
}

// ── Title page ────────────────────────────────────────────────────────────────

function buildTitlePage(meta: ReportMeta): DocChild[] {
  const scoreColor =
    meta.readinessScore >= 80 ? '16A34A' : meta.readinessScore >= 50 ? 'CA8A04' : 'DC2626'

  return [
    new Paragraph({
      children: [],
      spacing: { before: 2400, after: 0 },
    }),
    new Paragraph({
      children: [
        new TextRun({ text: 'Migration Readiness Report', bold: true, size: 52, font: 'Arial', color: '1E293B' }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { before: 0, after: 320 },
    }),
    new Paragraph({
      children: [
        new TextRun({ text: meta.projectName, size: 36, font: 'Arial', color: '4F46E5' }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { after: 240 },
    }),
    new Paragraph({
      children: [
        new TextRun({ text: `Generated: ${meta.generatedDate}`, size: 22, font: 'Arial', color: '64748B' }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    }),
    // Readiness score badge
    new Paragraph({
      children: [
        new TextRun({
          text: `${meta.readinessScore}%  —  ${meta.readinessLabel}`,
          bold: true,
          size: 32,
          font: 'Arial',
          color: scoreColor,
        }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { after: 800 },
    }),
    // Divider line via border
    new Paragraph({
      children: [],
      border: { bottom: { style: BorderStyle.SINGLE, size: 3, color: 'E2E8F0', space: 1 } },
      spacing: { after: 400 },
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: 'Confidential  ·  Generated by Mine AI Migration Platform',
          size: 18,
          font: 'Arial',
          color: '94A3B8',
          italics: true,
        }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { after: 0 },
    }),
    // Page break
    new Paragraph({
      children: [new PageBreak()],
    }),
  ]
}

// ── Section heading ───────────────────────────────────────────────────────────

function buildSectionHeading(title: string): Paragraph {
  return new Paragraph({
    heading: HeadingLevel.HEADING_1,
    children: [new TextRun({ text: title, bold: true, size: 28, font: 'Arial', color: '1E293B' })],
    spacing: { before: 480, after: 200 },
    border: {
      bottom: { style: BorderStyle.SINGLE, size: 2, color: 'E2E8F0', space: 6 },
    },
  })
}

// ── Markdown section parser ───────────────────────────────────────────────────

interface MarkdownSection {
  title: string
  content: string
}

function parseMarkdownSections(markdown: string): MarkdownSection[] {
  const sections: MarkdownSection[] = []

  // Remove the top-level # heading block (title / score metadata we handle in title page)
  const withoutH1 = markdown.replace(/^#[^#][^\n]*\n[\s\S]*?(?=^##|\z)/m, '')

  const parts = withoutH1.split(/^## /gm).filter(Boolean)

  for (const part of parts) {
    const newlineIdx = part.indexOf('\n')
    if (newlineIdx === -1) continue
    const title = part.substring(0, newlineIdx).trim()
    const content = part.substring(newlineIdx + 1).trim()
    if (!title) continue
    sections.push({ title, content })
  }

  return sections
}

// ── Content parser ────────────────────────────────────────────────────────────

function parseContentToDocChildren(content: string): DocChild[] {
  const children: DocChild[] = []
  const lines = content.split('\n')
  let i = 0

  while (i < lines.length) {
    const line = lines[i]

    if (line.trim() === '') {
      i++
      continue
    }

    // Markdown table block
    if (line.trim().startsWith('|')) {
      const tableLines: string[] = []
      while (i < lines.length && lines[i].trim().startsWith('|')) {
        tableLines.push(lines[i])
        i++
      }
      const parsed = parseMarkdownTable(tableLines)
      if (parsed) children.push(buildDocxTable(parsed))
      // Add spacing after table
      children.push(new Paragraph({ children: [], spacing: { after: 160 } }))
      continue
    }

    // Sub-heading ### 
    if (line.trim().startsWith('### ')) {
      children.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [
            new TextRun({
              text: line.trim().replace(/^### /, ''),
              bold: true,
              size: 24,
              font: 'Arial',
              color: '334155',
            }),
          ],
          spacing: { before: 280, after: 120 },
        })
      )
      i++
      continue
    }

    // Bullet list
    if (line.trim().match(/^[-*] /)) {
      children.push(
        new Paragraph({
          numbering: { reference: 'bullets', level: 0 },
          children: parseInlineFormatting(line.trim().replace(/^[-*] /, '')),
          spacing: { after: 80 },
        })
      )
      i++
      continue
    }

    // Numbered list
    if (line.trim().match(/^\d+\. /)) {
      children.push(
        new Paragraph({
          numbering: { reference: 'bullets', level: 0 },
          children: parseInlineFormatting(line.trim().replace(/^\d+\. /, '')),
          spacing: { after: 80 },
        })
      )
      i++
      continue
    }

    // Bold-only line (likely a mini-heading like **Field Name:**)
    if (line.trim().startsWith('**') && line.trim().endsWith('**') && !line.trim().slice(2, -2).includes('**')) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: line.trim().slice(2, -2), bold: true, size: 22, font: 'Arial' }),
          ],
          spacing: { before: 120, after: 80 },
        })
      )
      i++
      continue
    }

    // Regular paragraph
    children.push(
      new Paragraph({
        children: parseInlineFormatting(line.trim()),
        spacing: { after: 120 },
      })
    )
    i++
  }

  return children
}

// ── Inline bold/italic parser ─────────────────────────────────────────────────

function parseInlineFormatting(text: string): TextRun[] {
  const runs: TextRun[] = []
  // Match **bold**, `code`, or plain text segments
  const pattern = /(\*\*[^*]+\*\*|`[^`]+`)/g
  let last = 0
  let match: RegExpExecArray | null

  while ((match = pattern.exec(text)) !== null) {
    if (match.index > last) {
      runs.push(new TextRun({ text: text.slice(last, match.index), font: 'Arial', size: 22 }))
    }
    const raw = match[1]
    if (raw.startsWith('**')) {
      runs.push(new TextRun({ text: raw.slice(2, -2), bold: true, font: 'Arial', size: 22 }))
    } else {
      // backtick code — monospace
      runs.push(
        new TextRun({ text: raw.slice(1, -1), font: 'Courier New', size: 20, color: '475569' })
      )
    }
    last = match.index + raw.length
  }

  if (last < text.length) {
    runs.push(new TextRun({ text: text.slice(last), font: 'Arial', size: 22 }))
  }

  return runs.length > 0 ? runs : [new TextRun({ text, font: 'Arial', size: 22 })]
}

// ── Markdown table parser ─────────────────────────────────────────────────────

interface ParsedTable {
  headers: string[]
  rows: string[][]
}

function parseMarkdownTable(lines: string[]): ParsedTable | null {
  if (lines.length < 3) return null

  const parseRow = (line: string): string[] =>
    line
      .split('|')
      .map((cell) => cell.trim())
      .filter((cell) => cell && !cell.match(/^[-:]+$/))

  const headers = parseRow(lines[0])
  if (headers.length === 0) return null
  // lines[1] is the separator row (|---|---|)
  const rows = lines.slice(2).map(parseRow).filter((r) => r.length > 0)

  return { headers, rows }
}

// ── Docx Table builder ────────────────────────────────────────────────────────

function buildDocxTable(table: ParsedTable): Table {
  const colCount = table.headers.length
  // US Letter content width = 12240 - 2880 margins = 9360 twips
  const totalWidth = 9360
  const colWidth = Math.floor(totalWidth / colCount)
  const cellBorder = { style: BorderStyle.SINGLE, size: 4, color: 'E2E8F0' }
  const borders = { top: cellBorder, bottom: cellBorder, left: cellBorder, right: cellBorder }
  const cellMargins = { top: 80, bottom: 80, left: 100, right: 100 }

  const headerRow = new TableRow({
    tableHeader: true,
    children: table.headers.map(
      (h) =>
        new TableCell({
          borders,
          width: { size: colWidth, type: WidthType.DXA },
          shading: { fill: 'F1F5F9', type: ShadingType.CLEAR, color: 'auto' },
          margins: cellMargins,
          children: [
            new Paragraph({
              children: [
                new TextRun({ text: h, bold: true, font: 'Arial', size: 20, color: '1E293B' }),
              ],
            }),
          ],
        })
    ),
  })

  const dataRows = table.rows.map(
    (row) =>
      new TableRow({
        children: row.map(
          (cell) =>
            new TableCell({
              borders,
              width: { size: colWidth, type: WidthType.DXA },
              margins: cellMargins,
              children: [
                new Paragraph({
                  children: parseInlineFormatting(cell),
                }),
              ],
            })
        ),
      })
  )

  return new Table({
    width: { size: totalWidth, type: WidthType.DXA },
    columnWidths: Array(colCount).fill(colWidth),
    rows: [headerRow, ...dataRows],
  })
}
