-- Generated by Settle
-- Target table: t_customers
-- Source: Legacy CRM.s_customers
-- Generated: <UTC_TIMESTAMP>
-- Rows: 3

INSERT INTO "t_customers" ("t_customer_id", "t_full_name", "t_email_norm", "t_tenant_id") VALUES
('1', 'Alice Jones', 'alice@example.com', '00000000-0000-0000-0000-000000000001'),
('2', 'Bob O''Brien', NULL, '00000000-0000-0000-0000-000000000001'),
('3', 'Carol "C" Tran', 'carol@example.com', '00000000-0000-0000-0000-000000000001');
